version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-container
    networks:
      - internal_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/db_9solutions
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: urubu100
      SOLUTIONS_API_URL: http://127.0.0.1:5520/upload
    restart: unless-stopped